#!/bin/sh
set -eu

# Deletes files and sockets (not directories) that have not been accessed for
# more than 10 days in /tmp.
DAYS=10

find /tmp -type f,s -atime +${DAYS} -delete -exec echo Cleaning tmpdir: {} \;
