#!/bin/ksh

# /etc/rc.d/glances (Web server mode) script for OpenBSD.

# This file is licensed under WTFPL Version 2
# See the LICENSE file for more details:
# https://github.com/0x8100/handytools/blob/main/LICENSE

daemon="/usr/local/bin/glances"
daemon_flags="-w -B 127.0.0.1 -p 8080"
daemon_user="nobody"

. /etc/rc.d/rc.subr

rc_start() {
        rc_exec "${daemon} ${daemon_flags}" &
}

rc_check() {
        pgrep -f "python.* ${pexp}$"
}

rc_stop() {
        pkill -f "python.* ${pexp}$"
}

rc_reload=NO

rc_cmd $1
