#!/bin/sh
set -eu

# Delete files (except sockets) that have not been accessed for
# more than 10 days
find /tmp -type f -atime +10 -delete -exec echo Cleaning tmpdir: {} \;

# Delete empty directories that have not been changed for more than 10 days
find /tmp -type d -empty -mtime +10 -delete -exec echo Cleaning tmpdir: {} \;

# Delete VSCode sockets that have not been accessed for more than 10 days
find /tmp -type s -name 'vscode-*' -atime +10 -delete \
     -exec echo Cleaning tmpdir: {} \;
